{{- if .Values.dagArtifact.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-dag-artifact-{{ .Values.dagArtifact.commit | trunc 8 | replace "." "-" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Replace=true
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: sync-airflow-dag-artifact
      restartPolicy: Never

      containers:
        - name: dag-artifact-builder
          image: {{ .Values.dagArtifact.job.image }}
          imagePullPolicy: {{ .Values.dagArtifact.job.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              set -e

              echo "Cloning DAG repo..."
              git clone {{ .Values.dagArtifact.repo }} /repo
              cd /repo
              git checkout {{ .Values.dagArtifact.commit }}

              mkdir -p /workspace/dags
              cp -r {{ .Values.dagArtifact.subPath }}/* /workspace/dags/

              cd /workspace
              tar -czf dags.tar.gz dags

              echo "Creating ConfigMap artifact..."
              kubectl create configmap {{ .Values.dagArtifact.artifact.name }} \
                --from-file=dags.tar.gz \
                --dry-run=client -o yaml | kubectl apply -f -
      terminationGracePeriodSeconds: 30
{{- end }}
