############################################################
# DAG Artifact Distribution (Phase 2 - PVC Based)
############################################################

dagArtifact:
  enabled: true

  repo: https://github.com/rubenkam/sync-alternative
  branch: dags
  version: 1.0.0   # Git tag to deploy

  pvc:
    name: airflow-dag-artifact-pvc
    size: 1Gi
    storageClassName: standard


############################################################
# Apache Airflow Configuration
############################################################

airflow:

  useStandardNaming: true
  executor: KubernetesExecutor

  config:
    core:
      dags_folder: /opt/airflow/dags
      store_serialized_dags: True

  secrets:
    fernetKey:
      create: true

  dags:
    persistence:
      enabled: false
    gitSync:
      enabled: false

  scheduler:
    extraVolumes:
      - name: dag-artifact
        persistentVolumeClaim:
          claimName: airflow-dag-artifact-pvc

    extraVolumeMounts:
      - name: dag-artifact
        mountPath: /opt/airflow/dags

    podAnnotations:
      dag-version: "{{ .Values.dagArtifact.version }}"

  workers:
    extraVolumes:
      - name: dag-artifact
        persistentVolumeClaim:
          claimName: airflow-dag-artifact-pvc

    extraVolumeMounts:
      - name: dag-artifact
        mountPath: /opt/airflow/dags
