############################################################
# DAG Artifact Distribution (Phase 2 - PVC Based)
############################################################

dagArtifact:
  enabled: true

  repo: https://github.com/rubenkam/sync-alternative
  branch: dags
  version: v1.0.0   # Git tag to deploy

  pvc:
    name: airflow-dag-artifact-pvc
    size: 1Gi
    storageClassName: standard


############################################################
# Apache Airflow Configuration
############################################################

airflow:

  useStandardNaming: true
  executor: KubernetesExecutor

  config:
    core:
      dags_folder: /opt/airflow/dags
      store_serialized_dags: True

  secrets:
    fernetKey:
      create: true

  postgresql:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: latest

  dags:
    persistence:
      enabled: true
      existingClaim: airflow-dag-artifact-pvc
      accessMode: ReadWriteOnce   # fine for single-node local-path
    gitSync:
      enabled: false

  scheduler:
    podAnnotations:
      dag-version: "{{ .Values.dagArtifact.version }}"
      argocd.argoproj.io/sync-wave: "2"
